version: '3.9'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - quasar-fire-operation-svc
    ports:
      - "4000:4000"
  quasar-fire-operation-svc:
    build: .
    restart: on-failure
    environment:
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: secret
      APP_DB_NAME: quasar_fire_operation
      APP_DB_HOST: database
      APP_DB_PORT: 5432
    depends_on:
      - database
  database:
    image: "library/postgres:latest"
    command: [ "postgres", "-c", "log_statement=all" ]
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quasar_fire_operation