version: '3.8'

services:
  database:
    image: "library/postgres:latest"
    command: ["postgres", "-c", "log_statement=all"]
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quasar_fire_operation
    ports:
      - "5432:5432"
