version: '3.9'
services:
  test-app:
    image: golang:1.16
    volumes:
      - ".:$GOPATH/src/github.com/colombia9503/quasar-fire-operation"
    working_dir: $GOPATH/src/github.com/colombia9503/quasar-fire-operation
    user: root
    environment:
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: secret
      APP_DB_NAME: quasar_fire_operation
      APP_DB_HOST: database
      APP_DB_PORT: 5432
    depends_on:
      - database
    command: >
      sh -c "go get -v &&
      go test -v"